CREATE TABLE IF NOT EXISTS tipos_ato (
    codigo    INT PRIMARY KEY,
    descricao VARCHAR(255) NOT NULL,
    positivo  TEXT,
    negativo  TEXT
);

INSERT INTO tipos_ato (codigo, descricao, positivo, negativo) VALUES
(1,  'Citação',                              'CITEI',                                   'citação'),
(2,  'Intimação',                            'INTIMEI',                                 'intimação'),
(3,  'Notificação',                          'NOTIFIQUEI',                              'notificação'),
(4,  'Penhora',                              'procedi com a PENHORA dos bens',          'penhora'),
(5,  'Registro',                             'procedi com o REGISTRO',                  'registro'),
(6,  'Constatação',                          'procedi com a CONSTATAÇÃO',               'constatação'),
(7,  'Arrolamento',                          'procedi com o ARROLAMENTO dos bens',      'arrolamento'),
(8,  'Avaliação',                            'procedi com a AVALIAÇÃO dos bens',        'avaliação'),
(9,  'Arresto',                              'procedi com o ARRESTO',                   'arresto'),
(10, 'Sequestro',                            'procedi com o SEQUESTRO',                 'sequestro'),
(11, 'Arrecadação',                          'procedi com a ARRECADAÇÃO',               'arrecadação'),
(12, 'Lacramento',                           'procedi com o LACRAMENTO',                'lacramento'),
(13, 'Cautela',                              'procedi com a CAUTELA',                   'cautela'),
(14, 'Averbação',                            'procedi com a AVERBAÇÃO',                 'averbação'),
(15, 'Entrega',                              'procedi com a ENTREGA',                   'entrega'),
(16, 'Prisão',                               'efetuei a PRISÃO',                        'prisão'),
(17, 'Condução Coercitiva',                  'efetuei a CONDUÇÃO COERCITIVA',           'condução coercitiva'),
(18, 'Busca e Apreensão',                    'procedi com a BUSCA E APREENSÃO',         'busca e apreensão'),
(19, 'Reintegração de Posse',                'procedi com a REINTEGRAÇÃO DE POSSE',     'reintegração de posse'),
(20, 'Manutenção de Posse',                  'procedi com a MANUTENÇÃO DE POSSE',       'manutenção de posse'),
(21, 'Imissão de Posse',                     'procedi com a IMISSÃO DE POSSE',          'imissão de posse'),
(22, 'Separação de Corpos',                  'procedi com a SEPARAÇÃO DE CORPOS',       'separação de corpos'),
(23, 'Remoção',                              'procedi com a REMOÇÃO',                   'remoção'),
(24, 'Ofício',                               'cumpri o OFÍCIO',                         'ofício'),
(25, 'Alvará de Soltura',                    'cumpri o ALVARÁ DE SOLTURA',              'alvará de soltura'),
(26, 'Levantamento de Penhora',              'procedi com o LEVANTAMENTO DE PENHORA',   'levantamento de penhora'),
(27, 'Despejo',                              'procedi com o DESPEJO',                   'despejo'),
(28, 'Ordem',                                'cumpri a ORDEM',                          'ordem'),
(29, 'Restituição',                          'procedi com a RESTITUIÇÃO',               'restituição'),
(30, 'Exibição',                             'procedi com a EXIBIÇÃO',                  'exibição'),
(31, 'Interdito Proibitório',                'procedi com o INTERDITO PROIBITÓRIO',     'interdito proibitório'),
(32, 'Embargo de Obra Nova',                 'procedi com o EMBARGO DE OBRA NOVA',      'embargo de obra nova'),
(33, 'Outros/Diversos',                      'procedi com o ato',                       'outros/diversos'),
(34, 'Simples - Motivo não especificado',    NULL,                                      NULL),
(35, 'Endereço Incorreto',                   NULL,                                      NULL),
(36, 'Endereço Inexistente',                 NULL,                                      NULL),
(37, 'Ocultação Deliberada do Destinatário', NULL,                                      NULL),
(38, 'Motivo Viagem do Destinatário',        NULL,                                      NULL),
(39, 'Destinatário Mudou-se para L.I.N.S',  NULL,                                      NULL),
(40, 'Falta/Insuficiência da GRDD',          NULL,                                      NULL),
(41, 'Interessado Não Forneceu Condução',    NULL,                                      NULL),
(42, 'Interessado Não Forneceu Meios',       NULL,                                      NULL),
(43, 'Devolução a Pedido do Cartório',       NULL,                                      NULL),
(44, 'Solicitação de Prazo Pelo Oficial',    NULL,                                      NULL),
(45, 'Motivo Licenças do Oficial',           NULL,                                      NULL),
(46, 'Solicitação Reforço Policial',         NULL,                                      NULL),
(47, 'Pessoa Jurídica Desativada',           NULL,                                      NULL),
(48, 'Destinatário Falecido',                NULL,                                      NULL),
(49, 'Destinatário Mudou para Outra Comarca',NULL,                                      NULL),
(50, 'Não Localizou Bens do Destinatário',   NULL,                                      NULL),
(51, 'Cientificação',                        'CIENTIFIQUEI',                            'cientificação')
ON CONFLICT (codigo) DO NOTHING;
